<!--do not edit this file-->
<?php
require 'dbconfig.php';

session_start();

$user_id = $_SESSION['user_id'];
$username = $_SESSION['username'];

if (!isset($user_id)) {
    header('location:login.php');
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="./node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="./node_modules/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="./main.css">
</head>


<body class="bg-body-secondary bg-opacity-50">

    <?php require 'navbar.php' ?>

    <div class="container-fluid">
        <div class="row vh-100">
            <?php require 'customerSideBar.php' ?> <!--change the name to your sidebar file-->

            <div class="col-sm-12 col-lg-10">
                <div class="container min-vh-100">
                <h2>Place Your Order</h2>
        <form action="place_order.php" method="POST">
            <div class="form-group">
                <label for="orderPackage">Select Package</label>
                <select class="form-control" id="orderPackage" name="orderPackage">
                    <option value="P1">Package 1</option>
                    <option value="P2">Package 2</option>
                    <option value="P2">Package 3</option>
                </select>
            </div>
            <div class="form-group">
                <label for="paymentMethod">Payment Method</label>
                <select class="form-control" id="paymentMethod" name="paymentMethod">
                    <option value="Card">MembershipCard</option>
                    <option value="Cash">Cash</option>
                </select>
            </div>
            <div class="form-group">
                <label for="pickUpDate">Pick-Up Date</label>
                <input type="date" class="form-control" id="pickUpDate" name="pickUpDate">
            </div>
            <div class="form-group">
                <label for="pickUpTime">Pick-Up Time</label>
                <input type="time" class="form-control" id="pickUpTime" name="pickUpTime">
            </div>
            <button type="submit" class="btn btn-primary">Submit Order</button>
        </form>
                </div>

                <?php require 'footer.php' ?>
            </div>
        </div>
    </div>

    <script src="node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>


<!--
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.9.1/font/bootstrap-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="main.css">
</head>

<body class="bg-light">

    <div class="container">
        <h2>Place Your Order</h2>
        <form action="place_order.php" method="POST">
            <div class="form-group">
                <label for="orderPackage">Select Package</label>
                <select class="form-control" id="orderPackage" name="orderPackage">
                    <option value="P1">Package 1</option>
                    <option value="P2">Package 2</option>
                </select>
            </div>
            <div class="form-group">
                <label for="paymentMethod">Payment Method</label>
                <select class="form-control" id="paymentMethod" name="paymentMethod">
                    <option value="Card">Card</option>
                    <option value="Cash">Cash</option>
                </select>
            </div>
            <div class="form-group">
                <label for="pickUpDate">Pick-Up Date</label>
                <input type="date" class="form-control" id="pickUpDate" name="pickUpDate">
            </div>
            <div class="form-group">
                <label for="pickUpTime">Pick-Up Time</label>
                <input type="time" class="form-control" id="pickUpTime" name="pickUpTime">
            </div>
            <button type="submit" class="btn btn-primary">Submit Order</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>
